default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cheques_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: cheques_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV.fetch("DATABASE_URL") %>
    schema_search_path: public
  cache:
    <<: *primary_production
    schema_search_path: cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    schema_search_path: queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    schema_search_path: cable
    migrations_paths: db/cable_migrate